package DataDictionary.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EnumSimple {
  bool("bool", "logical"),
  varchar("varchar", "string"),
  date("date", "date"),
  double_4jl2xl_d("double", "double"),
  int_4jl2xl_e("int", "integer"),
  structure("structure", "structure");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EnumSimple(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EnumSimple> getConstants() {
    List<EnumSimple> list = ListSequence.fromList(new LinkedList<EnumSimple>());
    ListSequence.fromList(list).addElement(EnumSimple.bool);
    ListSequence.fromList(list).addElement(EnumSimple.varchar);
    ListSequence.fromList(list).addElement(EnumSimple.date);
    ListSequence.fromList(list).addElement(EnumSimple.double_4jl2xl_d);
    ListSequence.fromList(list).addElement(EnumSimple.int_4jl2xl_e);
    ListSequence.fromList(list).addElement(EnumSimple.structure);
    return list;
  }
  public static EnumSimple getDefault() {
    return EnumSimple.bool;
  }
  public static EnumSimple parseValue(String value) {
    if (value == null) {
      return EnumSimple.getDefault();
    }
    if (value.equals(EnumSimple.bool.getValueAsString())) {
      return EnumSimple.bool;
    }
    if (value.equals(EnumSimple.varchar.getValueAsString())) {
      return EnumSimple.varchar;
    }
    if (value.equals(EnumSimple.date.getValueAsString())) {
      return EnumSimple.date;
    }
    if (value.equals(EnumSimple.double_4jl2xl_d.getValueAsString())) {
      return EnumSimple.double_4jl2xl_d;
    }
    if (value.equals(EnumSimple.int_4jl2xl_e.getValueAsString())) {
      return EnumSimple.int_4jl2xl_e;
    }
    if (value.equals(EnumSimple.structure.getValueAsString())) {
      return EnumSimple.structure;
    }
    return EnumSimple.getDefault();
  }
}
