package DataDictionary.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Vertical;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.smodel.action.NodeFactoryManager;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.editor.menus.transformation.SNodeLocation;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;

/*package*/ class Dictionary_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Dictionary_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_ytbb8b_a();
  }

  private EditorCell createCollection_ytbb8b_a() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_ytbb8b_a");
    editorCell.setBig(true);
    editorCell.setCellContext(getCellFactory().getCellContext());
    editorCell.addEditorCell(createCollection_ytbb8b_a0());
    editorCell.addEditorCell(createConstant_ytbb8b_b0());
    editorCell.addEditorCell(createConstant_ytbb8b_c0());
    editorCell.addEditorCell(createConstant_ytbb8b_d0());
    editorCell.addEditorCell(createConstant_ytbb8b_e0());
    editorCell.addEditorCell(createConstant_ytbb8b_f0());
    editorCell.addEditorCell(createConstant_ytbb8b_g0());
    editorCell.addEditorCell(createConstant_ytbb8b_h0());
    editorCell.addEditorCell(createCollection_ytbb8b_i0());
    return editorCell;
  }
  private EditorCell createCollection_ytbb8b_a0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_ytbb8b_a0");
    Style style = new StyleImpl();
    style.set(StyleAttributes.SELECTABLE, false);
    editorCell.getStyle().putAll(style);
    editorCell.addEditorCell(createComponent_ytbb8b_a0a());
    editorCell.addEditorCell(createProperty_ytbb8b_b0a());
    return editorCell;
  }
  private EditorCell createComponent_ytbb8b_a0a() {
    EditorCell editorCell = getCellFactory().createEditorComponentCell(myNode, "jetbrains.mps.lang.core.editor.ShortDescriptionEditorComponent");
    return editorCell;
  }
  private EditorCell createProperty_ytbb8b_b0a() {
    CellProviderWithRole provider = new PropertyCellProvider(myNode, getEditorContext());
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_ytbb8b_b0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "-------------------------------------------------");
    editorCell.setCellId("Constant_ytbb8b_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ytbb8b_c0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "-------------------------------------------------");
    editorCell.setCellId("Constant_ytbb8b_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ytbb8b_d0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "-------------------------------------------------");
    editorCell.setCellId("Constant_ytbb8b_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ytbb8b_e0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "-------------------------------------------------");
    editorCell.setCellId("Constant_ytbb8b_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ytbb8b_f0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "");
    editorCell.setCellId("Constant_ytbb8b_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ytbb8b_g0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "");
    editorCell.setCellId("Constant_ytbb8b_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ytbb8b_h0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "");
    editorCell.setCellId("Constant_ytbb8b_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createCollection_ytbb8b_i0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Vertical());
    editorCell.setCellId("Collection_ytbb8b_i0");
    editorCell.addEditorCell(createRefNodeList_ytbb8b_a8a());
    return editorCell;
  }
  private EditorCell createRefNodeList_ytbb8b_a8a() {
    AbstractCellListHandler handler = new Dictionary_EditorBuilder_a.structuresListHandler_ytbb8b_a8a(myNode, "structures", getEditorContext());
    EditorCell_Collection editorCell = handler.createCells(new CellLayout_Vertical(), false);
    editorCell.setCellId("refNodeList_structures");
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }
  private static class structuresListHandler_ytbb8b_a8a extends RefNodeListHandler {
    @NotNull
    private SNode myNode;

    public structuresListHandler_ytbb8b_a8a(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      return NodeFactoryManager.createNode(MetaAdapterFactory.getInterfaceConcept(0xa7f45b2b89264555L, 0x82d3927859451525L, 0xdff9927af035b1aL, "DataDictionary.structure.Structure"), null, getNode(), getNode().getModel());
    }
    public EditorCell createNodeCell(SNode elementNode) {
      EditorCell elementCell = getUpdateSession().updateChildNodeCell(elementNode);
      installElementCellActions(elementNode, elementCell);
      return elementCell;
    }
    public EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(structuresListHandler_ytbb8b_a8a.this.getNode(), MetaAdapterFactory.getContainmentLink(0xa7f45b2b89264555L, 0x82d3927859451525L, 0xdff9927af035b14L, 0xdff9927af035b4bL, "structures")));
      try {
        EditorCell emptyCell = null;
        emptyCell = createConstant_ytbb8b_a0i0();
        installElementCellActions(null, emptyCell);
        setCellContext(emptyCell);
        return emptyCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    public void installElementCellActions(SNode elementNode, EditorCell elementCell) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.FORWARD));
          elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.BACKWARD));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
          elementCell.setSubstituteInfo(new SChildSubstituteInfo(elementCell, getNode(), MetaAdapterFactory.getContainmentLink(0xa7f45b2b89264555L, 0x82d3927859451525L, 0xdff9927af035b14L, 0xdff9927af035b4bL, "structures"), elementNode));
        }
      }
    }
    private EditorCell createConstant_ytbb8b_a0i0() {
      EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "------------------------------");
      editorCell.setCellId("Constant_ytbb8b_a0i0");
      editorCell.setDefaultText("");
      return editorCell;
    }
  }
}
